version: "3.9"
services:
  server:
    build: .
    ports:
      - "3000:3000"
      - "9999:9999"
    container_name: csofpn-server
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    container_name: csofpn-mongo